version: 2.1
workflows:
  testing:
    jobs:
      - printer-config
jobs:
  printer-config:
    machine: true
    resource_class: gokul-ceo/cloudprint
    steps:
      - run: git clone https://github.com/gokul-ceo/MQTT-Printer.git
      - run: cd MQTT-Printer
      - run: 
          name: Copy project to home
          command: | 
           mkdir -p ~/
           cp -r . ~/
      - run:
          name: Stop the service
          command: | 
           sudo systemctl stop PrintJob_script.service
      - run:
          name: Restart the service
          command: | 
           sudo systemctl daemon-reload
      - run: 
          name: Check Status of the service
          command: | 
           sudo systemctl restart PrintJob_script.service
