version: 2.1
workflows:
  testing:
    jobs:
      - printer-config
jobs:
  printer-config:
    machine: true
    resource_class: gokul-ceo/restyprinter
    steps:
      - run: git clone https://github.com/gokul-ceo/MQTT-Printer.git
      - run: cd MQTT-Printer
      - run:
          name: Copy project to home
          command: |
            sudo mkdir -p ~/restyagent
            sudo cp -r . ~/restyagent/
      - run:
          name: Stop the service
          command: |
            sudo systemctl stop restyprint.service
      - run:
          name: Restart the service
          command: |
            sudo systemctl daemon-reload
      - run:
          name: Start the service
          command: |
            sudo systemctl start restyprint.service
