version: 2.1
workflows:
  testing:
    jobs:
      - printer-config
jobs:
  printer-config:
    machine: true
    resource_class: gokul-ceo/cloudprint
    steps:
      - run: git clone https://github.com/gokul-ceo/MQTT-Printer.git
      - run: cd MQTT-Printer
      - run: mkdir -p /home/ubuntu/MQTT-Printer
             cp -r . /home/ubunut/MQTT-Printer
      
