version: 2.1
workflows:
  testing:
    jobs:
      - printer-config
jobs:
  printer-config:
    machine: true
    resource_class: gokul-ceo/cloudprint
    steps:
      - run: git clone https://github.com/gokul-ceo/MQTT-Printer.git
